defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 14
  reaping_frequency: 10

development:
  <<: *defaults
  database: twitter_dashboard_development

test: &test
  <<: *defaults
  database: twitter_dashboard_test


production:
  <<: *defaults
  database: twitter_dashboard_production
